### ISSUE TITLE
使用antd的时候样式丢一半是什么情况

### ISSUE THREAD

**Issue by liqingitt** [qyjandroid/react-project-template#1]

**Comment by qyjandroid** [comment]
好的，明天我验证一下!修改好给您回复



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月20日 19:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [qyjandroid/react-project-template] 使用antd的时候样式丢一半是什么情况 (Issue #1) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qyjandroid** [comment]
> _No description provided._

你好，你的是样式全部没有打包进去，还是？？可以提供下你的webpack.base.js 和 src/index.tsx 吗？？

**Comment by qyjandroid** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/6645414/150480896-8eb33cb6-934d-4892-b243-664f36fb3dcd.png)


我这边把webpack.base.js 里面的 ` {
          test: /\.css$|\.scss$/i,
        include: [SRC_PATH],
        exclude: /node_modules/,  
 }`
去掉 include 和 exclude 就可以了！！


在src/index.tsx 中引入 import 'antd/dist/antd.css';  样式
