### ISSUE TITLE
run start报错啊

### ISSUE THREAD

**Issue by susan-ontrack** [qyjandroid/react-project-template#3]
install 成功以后，run start就启动不起来了，报错信息如下，请问是我漏了什么配置吗？

我的node是v14.17.0

i ｢wdm｣: wait until bundle finished: /
× ｢wdm｣: ERROR in ./src/index.tsx
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
plugins.push(...).filter is not a function

    at module.exports (D:\front-demo\react-project-template\babel.config.js:53:8)
    at readConfigJS (D:\front-demo\react-project-template\node_modules\@babel\core\lib\config\files\configuration.js:227:15)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at step (D:\front-demo\react-project-template\node_modules\gensync\index.js:261:32)
    at evaluateAsync (D:\front-demo\react-project-template\node_modules\gensync\index.js:291:5)
    at Function.errback (D:\front-demo\react-project-template\node_modules\gensync\index.js:113:7)
    at errback (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:72:18)
    at async (D:\front-demo\react-project-template\node_modules\gensync\index.js:188:31)

webpack compiled with 1 error
i ｢wdm｣: Failed to compile.

**Comment by qyjandroid** [comment]
> install 成功以后，run start就启动不起来了，报错信息如下，请问是我漏了什么配置吗？
> 
> 我的node是v14.17.0
> 
> i ｢wdm｣: wait until bundle finished: / × ｢wdm｣: ERROR in ./src/index.tsx Module build failed (from ./node_modules/thread-loader/dist/cjs.js): Thread Loader (Worker 0) plugins.push(...).filter is not a function
> 
> ```
> at module.exports (D:\front-demo\react-project-template\babel.config.js:53:8)
> at readConfigJS (D:\front-demo\react-project-template\node_modules\@babel\core\lib\config\files\configuration.js:227:15)
> at readConfigJS.next (<anonymous>)
> at Function.<anonymous> (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
> at Generator.next (<anonymous>)
> at step (D:\front-demo\react-project-template\node_modules\gensync\index.js:261:32)
> at evaluateAsync (D:\front-demo\react-project-template\node_modules\gensync\index.js:291:5)
> at Function.errback (D:\front-demo\react-project-template\node_modules\gensync\index.js:113:7)
> at errback (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:72:18)
> at async (D:\front-demo\react-project-template\node_modules\gensync\index.js:188:31)
> ```
> 
> webpack compiled with 1 error i ｢wdm｣: Failed to compile.

![image](https://user-images.githubusercontent.com/6645414/172086305-52ee5fca-72cd-4df8-9ad3-4f56260f0901.png)
把babel.config.js 中这块注释掉试试

**Comment by qyjandroid** [comment]
> install 成功以后，run start就启动不起来了，报错信息如下，请问是我漏了什么配置吗？
> 
> 我的node是v14.17.0
> 
> i ｢wdm｣: wait until bundle finished: / × ｢wdm｣: ERROR in ./src/index.tsx Module build failed (from ./node_modules/thread-loader/dist/cjs.js): Thread Loader (Worker 0) plugins.push(...).filter is not a function
> 
> ```
> at module.exports (D:\front-demo\react-project-template\babel.config.js:53:8)
> at readConfigJS (D:\front-demo\react-project-template\node_modules\@babel\core\lib\config\files\configuration.js:227:15)
> at readConfigJS.next (<anonymous>)
> at Function.<anonymous> (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
> at Generator.next (<anonymous>)
> at step (D:\front-demo\react-project-template\node_modules\gensync\index.js:261:32)
> at evaluateAsync (D:\front-demo\react-project-template\node_modules\gensync\index.js:291:5)
> at Function.errback (D:\front-demo\react-project-template\node_modules\gensync\index.js:113:7)
> at errback (D:\front-demo\react-project-template\node_modules\@babel\core\lib\gensync-utils\async.js:72:18)
> at async (D:\front-demo\react-project-template\node_modules\gensync\index.js:188:31)
> ```
> 
> webpack compiled with 1 error i ｢wdm｣: Failed to compile.

已修复该问题，重新拉去即可

**Comment by qyjandroid** [comment]
已修复
